services:
  - type: web
    name: popdoc-backend
    env: node
    buildCommand: npm install
    startCommand: node server/index.js
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 3000